apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodb
  labels:
    app: demodb
spec:
  selector:
    matchLabels:
      app: demodb
  replicas: 1
  template:
    metadata:
      labels:
        app: demodb
    spec:
      containers:
      - name: demodb
        image: imranvisualpath/8amysql-db_1:V1
        ports:
        - name: demodb-port
          containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: "demodbpass"
